language: erlang

otp_release:
  - 17.1
  - 17.2
  - 17.3

env:
  - ELIXIR_VSN=1.0.0
  - ELIXIR_VSN=1.0.1
  - ELIXIR_VSN=1.0.2

install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VSN/Precompiled.zip
  - unzip -qq Precompiled.zip -d elixir

before_script:
  - export PATH=$PWD/elixir/bin:$PATH
  - export MIX_ENV=test
  - mix local.hex --force
  - mix deps.get

script: mix test --trace
